/*
 * Copyright (c) 2016 Google Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */

package com.google.samples.apps.iosched.sync.userdata.firebase;

/**
 * Callbacks for Firebase authentication.
 */
public interface FirebaseAuthCallbacks {

    /**
     * Fires when auth succeeds, passing the unique user id ({@code uid}) generated by {link
     * Firebase}.
     *
     * @param uid   The unique user id generated by Firebase.
     */
    void onAuthSucceeded(String uid);

    /**
     * Fires when auth fails.
     */
    void onAuthFailed();
}
