package com.google.samples.apps.iosched.util;


import android.content.Context;
import android.content.SharedPreferences;

import com.google.samples.apps.iosched.BuildConfig;

import java.util.ArrayList;
import java.util.zip.CRC32;

import static com.google.samples.apps.iosched.util.LogUtils.LOGI;
import static com.google.samples.apps.iosched.util.LogUtils.makeLogTag;

/**
 * Utility methods for setting up and interacting with a Firebase account associated with a user
 * account.
 */
public class FirebaseUtils {
    private static final String TAG = makeLogTag(AccountUtils.class);

    // These names are are prefixes; the account is appended to them.
    public static final String PREFIX_PREF_FIREBASE_UID = "firebase_uid_";
    public static final String PREFIX_PREF_FIREBASE_URL = "firebase_url_";

    /**
     * Stores the UID generated by Firebase in {@link SharedPreferences}.
     *
     * @param context Context used to lookup {@link SharedPreferences}.
     * @param uid     The user id (UID) generated by Firebase.
     */
    public static void setFirebaseUid(final Context context, final String accountName,
            final String uid) {
        LOGI(TAG, "Saving Firebase UID for accountName " + accountName);
        SharedPreferences sp = CommonUtils.getSharedPreferences(context);
        sp.edit().putString(
                AccountUtils.makeAccountSpecificPrefKey(context, PREFIX_PREF_FIREBASE_UID),
                uid).apply();
    }

    /**
     * Retrieves the Firebase UID associated with the current account stored in {@link
     * SharedPreferences}.
     *
     * @param context     Context used to lookup {@link SharedPreferences}.
     * @param accountName The account name associated with the chosen user account.
     * @return The Firebase UID associated with the current account.
     */
    public static String getFirebaseUrl(Context context, String accountName) {
        SharedPreferences sp = CommonUtils.getSharedPreferences(context);
        return sp.getString(
                AccountUtils.makeAccountSpecificPrefKey(accountName,
                        PREFIX_PREF_FIREBASE_URL), "");
    }

    /**
     * Calculates the Firebase url associated with an account id generated by calling {@link
     * com.google.android.gms.auth.GoogleAuthUtil#getAccountId(Context, String)}.
     *
     * @param context   Context used to lookup {@link SharedPreferences}.
     * @param accountId The account ID associated with the currently chosen account.
     */
    public static void setFirebaseUrl(Context context, String accountId) {
        String[] firebaseUrls = BuildConfig.FIREBASE_URLS;
        SharedPreferences sp = CommonUtils.getSharedPreferences(context);
        CRC32 crc = new CRC32();
        crc.update(accountId.getBytes());
        int index = (int) (crc.getValue() % firebaseUrls.length);
        LOGI(TAG, "Selected Firebase db # " + index);
        sp.edit().putString(
                AccountUtils.makeAccountSpecificPrefKey(context, PREFIX_PREF_FIREBASE_URL),
                firebaseUrls[index]).apply();
    }
}
